# Generated by Django 5.2.6 on 2025-12-05 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0003_chathistory_chatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User ID', max_length=100)),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('crop_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('images_json', models.JSONField(default=dict, help_text="{'whole': '/path/to/img1', 'close_up': '/path/to/img2'}")),
                ('final_diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('expert_diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('expert_notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisory.diagnosticsession')),
            ],
        ),
    ]
